### ISSUE TITLE
Auto select text when creating topic

### ISSUE THREAD

**Issue by Nordes** [season-studio/mind.svg.vue#3]
When you create a new topic, you should automatically select the text. This way it would avoid always doing a ctrl+A and then start typing.

Example: 
![image](https://user-images.githubusercontent.com/446572/90948917-8da1f580-e411-11ea-9ff8-1891bf0cb443.png)

Where it should be added:  `addSubTopic` and `addSiblingTopic`
Ref.: https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/select

Example of how it can be done:
https://github.com/Nordes/vsc.nano.mindmap/blob/dev/webview/src/App.vue#L330-L335

**Comment by season-studio** [comment]
It is a useful function. I have merged it in the new version.
But I think it is the best to make the change in function "editTopic". Because this function is the root function to active the edit action.
